---
- name: launch job from localhost and add data to remote server
  hosts: localhost
  tasks:
    - name: Add data to remote server
      community.postgresql.postgresql_db:
        name: patching
        state: present
        login_user: nrathi
        login_password: primod123
        login_host: 192.168.64.41

    - name: Create a table in the remote server
      community.postgresql.postgresql_table:
        name: userdata
        db: patching
        state: present
        login_user: nrathi
        login_password: primod123
        login_host: 192.168.64.41
