---
- name: launch job from localhost and add data to remote server
  hosts: localhost
  vars:
    pg_user: nrathi
    pg_password: primod123
  become: false
  gather_facts: false
  collections:
    - community.postgresql
  tasks:
    - name: Add data to remote server
      community.postgresql.postgresql_db:
        name: patching
        state: present
        login_user: nrathi
        login_password: primod123
        login_host: 192.168.64.41

    - name: Create a table in the remote server
      community.postgresql.postgresql_table:
        name: userdata
        login_db: patching
        state: present
        columns:
          - id serial primary key
          - fname text
          - lname text
        login_user: nrathi
        login_password: primod123
        login_host: 192.168.64.41

    - name: run a command on from localhost
      anisble.builtin.shell: microdnf install postgresql -y

    - name: Load data in db
      ansible.builtin.command: >
        psql -h 192.168.64.41 -U {{ pg_user }} -d patching
        -c "\copy userdata FROM '/path/on/ansible/host/userdata.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',')"
      environment:
        PGPASSWORD: "{{ pg_password }}"
      no_log: true

    - name: Load data in db 
      community.postgresql.postgresql_copy:
       login_db: patching
       login_user: nrathi
       login_password: primod123
       login_host: 192.168.64.41
       dst: userdata
       copy_from: userdata.csv
       options:
         delimiter: ','
         header: true
         format: csv