---
- name: launch job from localhost and add data to remote server
  hosts: localhost
  vars:
    pg_user: nrathi
    pg_password: primod123
    local_csv_path: userdata.csv
    db_name: patching
    db_host: 192.168.64.41
    db_port: 5432
    table_name: userdata

  become: false
  gather_facts: false
  collections:
    - community.postgresql

  tasks:
    - name: Add data to remote server
      community.postgresql.postgresql_db:
        name: patching
        state: present
        login_user: nrathi
        login_password: primod123
        login_host: 192.168.64.41

    - name: Create a table in the remote server
      community.postgresql.postgresql_table:
        name: userdata
        login_db: patching
        state: present
        columns:
          - id serial primary key
          - fname text
          - lname text
        login_user: nrathi
        login_password: primod123
        login_host: 192.168.64.41

### Working
    # - name: Load data in db
    #   ansible.builtin.command: >
    #     psql -h 192.168.64.41 -U {{ pg_user }} -d patching 
    #     -c "\copy userdata FROM 'userdata.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',')"
    #   environment:
    #     PGPASSWORD: "{{ pg_password }}"
    #   no_log: false
### Not working
    # - name: Load data in db 
    #   community.postgresql.postgresql_copy:
    #    login_db: patching
    #    login_user: nrathi
    #    login_password: primod123
    #    login_port: 5432
    #    login_host: 192.168.64.41
    #    dst: userdata
    #    copy_from: userdata.csv
    #    options:
    #      delimiter: ','
    #      header: true
    #      format: csv

    - name: Read local CSV file into memory
      community.general.read_csv:
        path: "{{ local_csv_path }}"
      register: csv_data

    - name: Bulk insert all rows in a single network request
      community.postgresql.postgresql_query:
        login_db: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ pg_user }}"
        login_password: "{{ pg_password }}"
        query: |
          INSERT INTO {{ table_name }} (id, fname, lname)
          VALUES 
          {% for row in item %}
          ('{{ row.Id }}', '{{ row.fname }}', '{{ row.lname }}'){% if not loop.last %},{% endif %}
          {% endfor %};
      loop: "{{ csv_data.list | slice( (csv_data.list | length / chunk_size) | text | float | ceil | int ) }}"    
      delegate_to: localhost    